### ISSUE TITLE
Error in Google Play Developer Console

### ISSUE THREAD

**Issue by xyther14** [alan-ai/alan-sdk-flutter#15]
Hi I released an internal testing for an app I created but Google Play developer console is showing this error. May I get some assistance here?

![image](https://user-images.githubusercontent.com/69085818/218735737-7274bd19-13ee-421e-b9dc-628c725869aa.png)

**Comment by snyuryev** [comment]
Hi @xyther14 
Which SDK version do you use?

**Comment by xyther14** [comment]
@snyuryev 
Dart SDK version: 2.19.2
Flutter 3.7.2

**Comment by snyuryev** [comment]
@xyther14 Alan_voice plugin version?

**Comment by xyther14** [comment]
@snyuryev 
alan_voice: ^3.10.0

**Comment by snyuryev** [comment]
@xyther14 Thank you! We will investigate this issue and update the plugin.

For internal testing you can also use Firebase App Distribution

**Comment by snyuryev** [comment]
Hi @xyther14 
You could try to use new version of the plugin - https://pub.dev/packages/alan_voice/versions/3.12.0
The issue should be resolved
