### ISSUE TITLE
Alan button hide does not work

### ISSUE THREAD

**Issue by Merculiar** [alan-ai/alan-sdk-flutter#16]
I want to hide the alan button in my project and activate/deactivate it programmatically with my own button (with activate/deactivate methods).
Every time I call to activate, the button is hidden and works fine, but when I call deactivate, the button appears again and the hide method does nothing.

**Comment by snyuryev** [comment]
Hi @Merculiar,

Could you provide steps how we can reproduce this issue? What version of AlanSDK do you use? What platform do you use? iOS or Android?

**Comment by Merculiar** [comment]
AlanSdk version 4.1.1, Android platform.
1) AlanVoice.addButton
2) AlanVoice.hideButton(); (on this step floating Alan button is hidden)
3) Made custom button with AlanVoice.activate()/AlanVoice.deactivate() functionality
4) Each time I press AlanVoice.deactivate() floating Alan button appears again

**Comment by snyuryev** [comment]
Hi @Merculiar 
This issue will be fixed with next plugin update.

**Comment by snyuryev** [comment]
hi @Merculiar new version of plugin (v 4.2.0) is released
https://pub.dev/packages/alan_voice/versions/4.2.0
Hope that will help with this issue

**Comment by Merculiar** [comment]
Just spotted that I can hide it in the settings of Alan Studio! Thanks, closing.
