### ISSUE TITLE
Android Alan Button Issue

### ISSUE THREAD

**Issue by imcoffeefreak** [alan-ai/alan-sdk-flutter#3]
Alan Button disappears in release mode
`flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi`

Error displayed:
`Failed to add Alan button PlatformException(error, Subscriber class com.alan.alansdk.button.a and its super classes have no public methods with the @Subscribe annotation, null, m.a.a.e: Subscriber class com.alan.alansdk.button
.a and its super classes have no public methods with the @Subscribe annotation
`

**Comment by snyuryev** [comment]
@imcoffeefreak 
What is device model and Android version on this device?

btw 
the preferable way to build release for flutter is using command: 
`flutter build appbundle`
(The Google Play Store prefers the app bundle format)

if you want to build apk please try to use command:
`flutter build apk --split-per-abi`
(without --target-platform option)

**Comment by imcoffeefreak** [comment]
> @imcoffeefreak
> What is device model and Android version on this device?
> 
> btw
> the preferable way to build release for flutter is using command:
> `flutter build appbundle`
> (The Google Play Store prefers the app bundle format)
> 
> if you want to build apk please try to use command:
> `flutter build apk --split-per-abi`
> (without --target-platform option)


Model: RealMe 5 Pro

`flutter build apk --split-per-abi` does not work either

**Comment by snyuryev** [comment]
got it.
How do you add Alan Button in the flutter app?
`AlanVoice.addButton("8e0b083e795c924d64635bba9c3571f42e956eca572e1d8b807a3e2338fdd0dc/stage");`
something like that?

**Comment by imcoffeefreak** [comment]
> got it.
> How do you add Alan Button in the flutter app?
> `AlanVoice.addButton("8e0b083e795c924d64635bba9c3571f42e956eca572e1d8b807a3e2338fdd0dc/stage");`
> something like that?

Yes

**Comment by rohitghosal** [comment]
# need help
Alan Button disappears in release mode of Flutter build apk
And got stuck also in debug mode in android 10 nokia 6.1plus

**Comment by snyuryev** [comment]
@rohitghosal @imcoffeefreak 

Please try to add additional params for release build type
```
shrinkResources false
minifyEnabled false
```
to your build.gradle file. It should be located
```
[your_app_folder]/android/app/build.gradle
```

As result you should have something similar to:
```
buildTypes {
        release {
            signingConfig signingConfigs.debug
            shrinkResources false
            minifyEnabled false
        }
  }
```

After that please try to run 
```
flutter build apk
```
and run your app.

**Comment by imcoffeefreak** [comment]
@snyuryev 

Works good !!!!

> @rohitghosal @imcoffeefreak
> 
> Please try to add additional params for release build type
> 
> ```
> shrinkResources false
> minifyEnabled false
> ```
> 
> to your build.gradle file. It should be located
> 
> ```
> [your_app_folder]/android/app/build.gradle
> ```
> 
> As result you should have something similar to:
> 
> ```
> buildTypes {
>         release {
>             signingConfig signingConfigs.debug
>             shrinkResources false
>             minifyEnabled false
>         }
>   }
> ```
> 
> After that please try to run
> 
> ```
> flutter build apk
> ```
> 
> and run your app.

**Comment by snyuryev** [comment]
@imcoffeefreak I'm glad to help you!
