### ISSUE TITLE
Alan Button and working disappear in Flutter release aok

### ISSUE THREAD

**Issue by rohitghosal** [alan-ai/alan-sdk-flutter#4]
# Alan Button disappears in Flutter release apk

I  almost perfectly implemented everything and works on debug mode on android 8/9 device something sticks with Android 10 . More strange when I see the whole Alan functionality with its button completely vanished from the release apk of the Flutter integrated project

**Comment by rohitghosal** [comment]
I used SDK key as "<SDK KEY OF  ALAN/stage>" should I use prod instead??

**Comment by snyuryev** [comment]
@rohitghosal 

Please try to add additional params for release build type

```
shrinkResources false
minifyEnabled false
```

to your build.gradle file. It should be located
```
[your_app_folder]/android/app/build.gradle
```

As result you should have something similar to:
```
buildTypes {
        release {
            signingConfig signingConfigs.debug
            shrinkResources false
            minifyEnabled false
        }
  }
```

After that please try to run 
```
flutter build apk
```
and run your app.

**Comment by rohitghosal** [comment]
I tried with that again same result no button no voice ai integration

**Comment by snyuryev** [comment]
@rohitghosal 

Please try our [simple example](https://github.com/alan-ai/alan-sdk-flutter/tree/master/examples/alan_simple_app)
That was built and tested on Android 10 as well.

**Comment by rohitghosal** [comment]
Ok sure and send you the update very soon..and thanks for helping

**Comment by rohitghosal** [comment]
one more doubt at button integration time would the sdk key in prod mode
like "<SDK key>/prod" for enable alan in release apk?

**Comment by snyuryev** [comment]
@rohitghosal 
It is not necessary to use "/prod" for release apk. You can use "/stage"

But it is better to use "/prod" version of your script - just to make sure that your script will have stable version.

**Comment by rohitghosal** [comment]
Ok trying once again..and updating you

**Comment by rohitghosal** [comment]
many many thanks sir, i just deleted all previous build and now rerun and
finally working..fine...grateful to you.

**Comment by snyuryev** [comment]
@rohitghosal I'm glad to help you!

**Comment by chinnuchitti0128** [comment]
Yeah...my Alan button is also disappeared when I bulid in release mode . Can u provide solution ??

**Comment by snyuryev** [comment]
@chinnuchitti0128 Please take a look to #3
