### ISSUE TITLE
Alan Voice

### ISSUE THREAD

**Issue by AvdhootJadhav** [alan-ai/alan-sdk-flutter#5]
I followed the official documentation to build a simple Alan Voice app. I did follow all the steps. But as soon as I click on the Alan voice button everything crahes down. The app gets closed automatically. Why is that so?

**Comment by snyuryev** [comment]
Hey @AvdhootJadhav 
Please provide more information about your issue. (plugin version, OS, OS version).

Also please try to run our [simple app](https://github.com/alan-ai/alan-sdk-flutter/tree/master/examples/alan_simple_app) - do you have the same issue with this app?
