### ISSUE TITLE
Null safety support for flutter 

### ISSUE THREAD

**Issue by FadiChaalab** [alan-ai/alan-sdk-flutter#7]
Could you migrate your project to null safety, your package is awesome but i can't use it because it doesn't support null safety.

**Comment by adamsyy** [comment]
if you want to use alan in your application, you can run your app without null safety.
put //@Dart=2.9 as the first line in main.dart file (even before the import statements) and then rebuild you application once again

**Comment by snyuryev** [comment]
v 3.0.0 with null safety support is released
