### ISSUE TITLE
Flutter IOS application crashes in the startup.

### ISSUE THREAD

**Issue by Ilthizam** [alan-ai/alan-sdk-flutter#8]
Flutter IOS application crashes in the startup.
```
Flutter 2.0.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b1395592de (3 months ago) • 2021-04-01 14:25:01 -0700
Engine • revision 2dce47073a
Tools • Dart 2.12.2

IOS targeted version:  12.1


alan_voice: ^2.2.0

```

**Comment by snyuryev** [comment]
@Ilthizam could you provide some logs with crash issue?

**Comment by Ilthizam** [comment]
> @Ilthizam could you provide some logs with crash issue?

```
objc[1209]: Class AMSupportURLConnectionDelegate is implemented in both ?? (0x20f9c4188) and ?? (0x117de82b8). One of the two will be used. Which one is undefined.
objc[1209]: Class AMSupportURLSession is implemented in both ?? (0x20f9c41d8) and ?? (0x117de8308). One of the two will be used. Which one is undefined.
Launching lib/main.dart on iPhone 12 Pro Max in debug mode...
Running pod install...                                           1,334ms
Running Xcode build...                                                  
 └─Compiling, linking and signing...                         6.4s
Xcode build done.                                           24.5s
Lost connection to device.


XCode logs

Ld /Users/ilthizamimtiyas/Library/Developer/Xcode/DerivedData/Runner-dhbhdiavdcxxdmglecijwyzyqodd/Build/Products/Debug-iphonesimulator/alan_voice/alan_voice.framework/alan_voice normal (in target 'alan_voice' from project 'Pods')
    cd /Users/ilthizamimtiyas/Desktop/test_ai/ios/Pods
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target arm64-apple-ios11.0-simulator -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk -L/Users/ilthizamimtiyas/Library/Developer/Xcode/DerivedData/Runner-dhbhdiavdcxxdmglecijwyzyqodd/Build/Products/Debug-iphonesimulator/alan_voice -F/Users/ilthizamimtiyas/Library/Developer/Xcode/DerivedData/Runner-dhbhdiavdcxxdmglecijwyzyqodd/Build/Products/Debug-iphonesimulator/alan_voice -F/Users/ilthizamimtiyas/Developments/flutter/bin/cache/artifacts/engine/ios/Flutter.xcframework/ios-x86_64-simulator -F/Users/ilthizamimtiyas/Desktop/test_ai/ios/Pods/../.symlinks/plugins/alan_voice/ios/Frameworks -filelist /Users/ilthizamimtiyas/Library/Developer/Xcode/DerivedData/Runner-dhbhdiavdcxxdmglecijwyzyqodd/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/alan_voice.build/Objects-normal/arm64/alan_voice.LinkFileList -install_name @rpath/alan_voice.framework/alan_voice -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/ilthizamimtiyas/Library/Developer/Xcode/DerivedData/Runner-dhbhdiavdcxxdmglecijwyzyqodd/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/alan_voice.build/Objects-normal/arm64/alan_voice_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -fobjc-arc -fobjc-link-runtime -framework Flutter -framework Foundation -Xlinker -no_adhoc_codesign -compatibility_version 1 -current_version 1 -Xlinker -dependency_info -Xlinker /Users/ilthizamimtiyas/Library/Developer/Xcode/DerivedData/Runner-dhbhdiavdcxxdmglecijwyzyqodd/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/alan_voice.build/Objects-normal/arm64/alan_voice_dependency_info.dat -o /Users/ilthizamimtiyas/Library/Developer/Xcode/DerivedData/Runner-dhbhdiavdcxxdmglecijwyzyqodd/Build/Products/Debug-iphonesimulator/alan_voice/alan_voice.framework/alan_voice

ld: warning: ignoring file /Users/ilthizamimtiyas/Developments/flutter/bin/cache/artifacts/engine/ios/Flutter.xcframework/ios-x86_64-simulator/Flutter.framework/Flutter, building for iOS Simulator-arm64 but attempting to link with file built for iOS Simulator-x86_64
ld: warning: building for iOS Simulator, but linking in dylib built for iOS, 'AlanSDK.framework'
ld: warning: Could not find or use auto-linked framework 'AlanSDK'
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_AlanConfig", referenced from:
      objc-class-ref in AlanVoicePlugin.o
  "_OBJC_CLASS_$_FlutterMethodChannel", referenced from:
      objc-class-ref in AlanVoicePlugin.o
  "_OBJC_CLASS_$_AlanLog", referenced from:
      objc-class-ref in AlanVoicePlugin.o
  "_OBJC_CLASS_$_FlutterError", referenced from:
      objc-class-ref in AlanVoicePlugin.o
  "_OBJC_CLASS_$_AlanButton", referenced from:
      objc-class-ref in AlanVoicePlugin.o
  "_OBJC_CLASS_$_FlutterEventChannel", referenced from:
      objc-class-ref in AlanVoicePlugin.o
  "_OBJC_CLASS_$_AlanText", referenced from:
      objc-class-ref in AlanVoicePlugin.o
  "_FlutterMethodNotImplemented", referenced from:
      -[AlanVoicePlugin handleMethodCall:result:] in AlanVoicePlugin.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)



```

**Comment by snyuryev** [comment]
@Ilthizam can you share logs from Xcode console?

**Comment by Ilthizam** [comment]
> @Ilthizam can you share logs from Xcode console?

Ld /Users/ilthizamimtiyas/Library/Developer/Xcode/DerivedData/Runner-dhbhdiavdcxxdmglecijwyzyqodd/Build/Products/Debug-iphonesimulator/alan_voice/alan_voice.framework/alan_voice normal (in target 'alan_voice' from project 'Pods')
    cd /Users/ilthizamimtiyas/Desktop/test_ai/ios/Pods
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target arm64-apple-ios11.0-simulator -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk -L/Users/ilthizamimtiyas/Library/Developer/Xcode/DerivedData/Runner-dhbhdiavdcxxdmglecijwyzyqodd/Build/Products/Debug-iphonesimulator/alan_voice -F/Users/ilthizamimtiyas/Library/Developer/Xcode/DerivedData/Runner-dhbhdiavdcxxdmglecijwyzyqodd/Build/Products/Debug-iphonesimulator/alan_voice -F/Users/ilthizamimtiyas/Developments/flutter/bin/cache/artifacts/engine/ios/Flutter.xcframework/ios-x86_64-simulator -F/Users/ilthizamimtiyas/Desktop/test_ai/ios/Pods/../.symlinks/plugins/alan_voice/ios/Frameworks -filelist /Users/ilthizamimtiyas/Library/Developer/Xcode/DerivedData/Runner-dhbhdiavdcxxdmglecijwyzyqodd/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/alan_voice.build/Objects-normal/arm64/alan_voice.LinkFileList -install_name @rpath/alan_voice.framework/alan_voice -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/ilthizamimtiyas/Library/Developer/Xcode/DerivedData/Runner-dhbhdiavdcxxdmglecijwyzyqodd/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/alan_voice.build/Objects-normal/arm64/alan_voice_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -fobjc-arc -fobjc-link-runtime -framework Flutter -framework Foundation -Xlinker -no_adhoc_codesign -compatibility_version 1 -current_version 1 -Xlinker -dependency_info -Xlinker /Users/ilthizamimtiyas/Library/Developer/Xcode/DerivedData/Runner-dhbhdiavdcxxdmglecijwyzyqodd/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/alan_voice.build/Objects-normal/arm64/alan_voice_dependency_info.dat -o /Users/ilthizamimtiyas/Library/Developer/Xcode/DerivedData/Runner-dhbhdiavdcxxdmglecijwyzyqodd/Build/Products/Debug-iphonesimulator/alan_voice/alan_voice.framework/alan_voice

ld: warning: ignoring file /Users/ilthizamimtiyas/Developments/flutter/bin/cache/artifacts/engine/ios/Flutter.xcframework/ios-x86_64-simulator/Flutter.framework/Flutter, building for iOS Simulator-arm64 but attempting to link with file built for iOS Simulator-x86_64
ld: warning: building for iOS Simulator, but linking in dylib built for iOS, 'AlanSDK.framework'
ld: warning: Could not find or use auto-linked framework 'AlanSDK'
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_AlanConfig", referenced from:
      objc-class-ref in AlanVoicePlugin.o
  "_OBJC_CLASS_$_FlutterMethodChannel", referenced from:
      objc-class-ref in AlanVoicePlugin.o
  "_OBJC_CLASS_$_AlanLog", referenced from:
      objc-class-ref in AlanVoicePlugin.o
  "_OBJC_CLASS_$_FlutterError", referenced from:
      objc-class-ref in AlanVoicePlugin.o
  "_OBJC_CLASS_$_AlanButton", referenced from:
      objc-class-ref in AlanVoicePlugin.o
  "_OBJC_CLASS_$_FlutterEventChannel", referenced from:
      objc-class-ref in AlanVoicePlugin.o
  "_OBJC_CLASS_$_AlanText", referenced from:
      objc-class-ref in AlanVoicePlugin.o
  "_FlutterMethodNotImplemented", referenced from:
      -[AlanVoicePlugin handleMethodCall:result:] in AlanVoicePlugin.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by snyuryev** [comment]
@Ilthizam are you running the code on Mac with Apple Silicon?

**Comment by Ilthizam** [comment]
> @Ilthizam are you running the code on Mac with Apple Silicon?

yes

**Comment by snyuryev** [comment]
Got it. As workaround I can suggest you to follow next steps. In the XCode project, go to Build Settings:
1. Set the Excluded Architectures option to arm64 (EXCLUDED_ARCHS = arm64).
2. Set the Validate Workspace option to YES (VALIDATE_WORKSPACE = YES).
3. Set the Enable Bitcode option to NO (ENABLE_BITCODE = NO).
